Controllers/CurriculoController.cs
using MeuCurriculo.Model;
using Microsoft.AspNetCore.Mvc;

public class CurriculoController : Controller
{
    private readonly HttpClient _http;

    public CurriculoController(IHttpClientFactory httpClientFactory)
    {
        _http = httpClientFactory.CreateClient("MeuCurriculoClient");
    }

    public async Task<IActionResult> CurriculoIndex()
    {
       
        var experiencias = await _http.GetFromJsonAsync<List<ExperienciaModel>>("/api/experiencia");
        var formacoes = await _http.GetFromJsonAsync<List<FormacaoModel>>("/api/formacao");
        var idiomas = await _http.GetFromJsonAsync<List<IdiomaModel>>("/api/idioma");
        var hardskills = await _http.GetFromJsonAsync<List<HardSkillsModel>>("/api/hardskills");
        var softskills = await _http.GetFromJsonAsync<List<SoftSkillsModel>>("/api/softskills");

        var model = new CurriculoViewModel
        {
            Nome = "João Antonio de Lima França",
            Funcao = "Junior Software Developer",
            Sobremim = "Sou um profissional em transição de carreira, atualmente iniciando minha jornada na área de desenvolvimento de software. Tenho 24 anos, resido em São Carlos, SP e estou cursando Análise e Desenvolvimento de Sistemas pela FIAP. Tenho experiência em áreas da tecnologia, como montagem e manutenção eletrônica, além de reparo de microcomputadores. Tenho grande interesse por tecnologia, resolução de problemas e criação de soluções que façam a diferença. Estou em busca da minha primeira oportunidade como desenvolvedor. Sou dedicado, curioso, gosto de aprender na prática e procuro evoluir sempre com desafios. Meus conhecimentos estão mais detalhados abaixo.",

            Experiencias = experiencias,
            Formacoes = formacoes,
            Idiomas = idiomas,
            HardSkills = hardskills,
            SoftSkills = softskills
        };

        return View(model);
    }
}

Controllers/ExperienciaController.cs
using MeuCurriculo.Model;
using Microsoft.AspNetCore.Mvc;

namespace MeuCurriculo.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ExperienciaController : ControllerBase
    {
        [HttpGet]

        public IActionResult Get()
        {
            var experiencia = new List<ExperienciaModel>
            {
                new ExperienciaModel
                {
                    Empresa = "DMC Equipamentos",
                    Cargo = "Montador de Equipamentos Eletrônicos",
                    Periodo = "Set/2023 - Jul/2025",
                    DescricaoCargo = "Produção e montagem de equipamentos médicos, estéticos e odontológicos " +
                    "Atuação com eletrônica digital, mecânica e controle de qualidade dos produtos."
                },

                new ExperienciaModel
                {
                    Empresa = "DirectLight",
                    Cargo = "Montador de Equipamentos Elétricos",
                    Periodo = "Set/2022 - Set/2023",
                    DescricaoCargo = "Manutenção, montagem e fabricação de produtos de iluminação interna e externa com alto rendimento luminoso"

                },

                new ExperienciaModel
                {
                    Empresa = "Compuled",
                    Cargo = "Técnico em Manutenção de Equipamentos de Informática",
                    Periodo = "Abr/2022 - Ago/2022",
                    DescricaoCargo = "Realização de formatação de sistemas, manutenção preventiva e corretiva, recuperação de dados, configuração e execução de backups. Responsável também pelo reparo, otimização e atualização de microcomputadores, garantindo desempenho e estabilidade dos equipamentos."
                }


            };

            return Ok(experiencia);
        }
    }
}

Controllers/FormacaoController.cs
using MeuCurriculo.Model;
using Microsoft.AspNetCore.Mvc;

namespace MeuCurriculo.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class FormacaoController : ControllerBase
    {
        [HttpGet]

        public IActionResult Get()
        {
            var formacao = new List<FormacaoModel>
            {
                new FormacaoModel
                {
                    Instituicao = "FIAP - Faculdade de Informática e Administração Paulista",
                    Curso = "Análise e Desenvolvimento de Sistemas",
                    DataInicio = new DateOnly(2024, 2, 1),
                    DataFim = new DateOnly(2025, 12, 31)
                },
                new FormacaoModel
                {
                    Instituicao = "Etec Paulino Botelho",
                    Curso = "Técnico em Eletrônica Integrado ao Ensino Médio",
                    DataInicio = new DateOnly(2018, 2, 1),
                    DataFim = new DateOnly(2020, 12, 31)
                }
            }; return Ok(formacao);
        
        }

        
    }
}

Controllers/HardSkillsController.cs
using MeuCurriculo.Model;
using Microsoft.AspNetCore.Mvc;

namespace MeuCurriculo.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class HardSkillsController : ControllerBase
    {
        [HttpGet]
        public IActionResult Get()
        {
            var hardskills = new List<HardSkillsModel>
            {
                new HardSkillsModel { HardSkills = "Java" },
                new HardSkillsModel { HardSkills = "Python" },
                new HardSkillsModel { HardSkills = "Kotlin" },
                new HardSkillsModel { HardSkills = "C#" },
                new HardSkillsModel { HardSkills = "HTML" },
                new HardSkillsModel { HardSkills = "CSS" },
                new HardSkillsModel { HardSkills = "JavaScript" },
                new HardSkillsModel { HardSkills = "API RESTful" },
                new HardSkillsModel { HardSkills = "Git" },
                new HardSkillsModel { HardSkills = "Docker" },
                new HardSkillsModel { HardSkills = "Oracle SQL" },
                new HardSkillsModel { HardSkills = "Spring Boot" },
                new HardSkillsModel { HardSkills = "Scrum" },
                new HardSkillsModel { HardSkills = "Kanban" },


                
            };
            return Ok(hardskills);
        }


    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace MeuCurriculo.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult IndexHome()
        {
            return View();
        }
    }
}

Controllers/IdiomaController.cs
using MeuCurriculo.Model;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MeuCurriculo.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class IdiomaController : ControllerBase
    {
        [HttpGet]

        public IActionResult Get()
        {
            var idioma = new List<IdiomaModel>
            {
                new IdiomaModel
                {
                    Idioma = "Inglês",
                    Nivel = "Intermediário em processo de aperfeiçoamento"
                }

            };
            return Ok(idioma);
        }
    }
}

Controllers/SoftSkillsController.cs
using MeuCurriculo.Model;
using Microsoft.AspNetCore.Mvc;

namespace MeuCurriculo.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class SoftSkillsController : ControllerBase
    {
        [HttpGet]
        public IActionResult Get()
        {
            var softskills = new List<SoftSkillsModel>
            {
                new SoftSkillsModel { SoftSkills = "Trabalho em equipe" },
                new SoftSkillsModel { SoftSkills = "Proativo" },
                new SoftSkillsModel { SoftSkills = "Rapido aprendizado" },
                new SoftSkillsModel { SoftSkills = "Adaptabilidade" },
            };
            return Ok(softskills);
        }


    }
}

Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MeuCurriculo.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MeuCurriculo.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.0/css/all.min.css" integrity="sha512-DxV+EoADOkOygM4IR9yXP8Sb2qwgidEmeqAEmDKIOfPRQZOWbXCzLC6vjbZyy0vPisbH2SyW27+ddLVCN+OMzQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
    <header>
    @await RenderSectionAsync("Scripts", required: false)
    </header>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js"></script>
</body>

</html>

Views/Curriculo/CurriculoIndex.cshtml
@using MeuCurriculo.Model

@section Scripts {
    <script src="~/js/curriculojs.js"></script>
}

@{
    Layout = "_Layout";
    ViewData["Title"] = "Currículo João";
}

<link rel="stylesheet" href="~/css/curriculosyle.css" asp-append-version="true" />

<div class="curriculo-container">
    <div class="curriculo-card scroll-card">    
        <h1>@Model.Nome</h1>
        <h3>@Model.Funcao</h3>

        
        <div class="contato">
            <a href="#" onclick="copiarNumero(this)" class="btn-contato grow-hover btn-telefone" data-numero="16991354633"><i class="fas fa-phone"></i>Telefone</a>
            <a href="https://wa.me/16991354633?text=Olá João,%20vi%20seu%20currículo%20e%20gostaria%20de%20entrar%20em%20contato." class="btn-contato btn-whatsapp" target="_blank"><i class="fab fa-whatsapp"></i>WhatsApp</a>
            <a href="mailto:jho_jbbantonio11@live.com" class="btn-contato grow-hover btn-email" target="_blank"><i class="fas fa-envelope"></i>Email</a>
            <a href="https://www.linkedin.com/in/joao-franca-808180229" class="btn-contato btn-linkedin" target="_blank"><i class="fab fa-linkedin"></i>LinkedIn</a>
            <a href="https://github.com/Jonastheprogram" class="btn-contato btn-github" target="_blank"><i class="fab fa-github"></i>GitHub</a>
        </div>
    </div>

    <div id="toast-container"></div>

    <div class="curriculo-card containerS mt-5 scroll-card">
        <h2>Sobre Mim</h2>
        <p id="sobremim">@Model.Sobremim</p>
    </div>

    <div class="curriculo-card mt-5 scroll-card">
        <h2>Experiência Profissional</h2>
        @foreach (var e in Model.Experiencias)
        {
            <div>
                <h5>@e.Cargo</h5>
                <p>@e.Empresa</p>
                <p>@e.Periodo</p>
                <p>@e.DescricaoCargo</p>
            </div>
        }
    </div>

    <div class="curriculo-card mt-5 scroll-card">
        <h2>Formação Acadêmica</h2>
        @foreach (var f in Model.Formacoes)
        {
            <div>
                <h5>@f.Curso</h5>
                <p>@f.Instituicao</p>
                 <p>@f.DataInicio — @f.DataFim</p>
            </div>
        }
    </div>

    <div class="curriculo-card mt-5 scroll-card">
        <h2>Idiomas</h2>
        @foreach (var i in Model.Idiomas)
        {
            <p>@i.Idioma — @i.Nivel</p>
        }
    </div>

    <div class="curriculo-card mt-5 scroll-card">
        <h3>Hard Skills</h3>
        <div class="skills-container" id="hardskills">
            @foreach (var s in Model.HardSkills)
            {
                <span class="skill-badge">@s.HardSkills</span>
            }</div>

        <h3>Soft Skills</h3>
        <div class="skills-container" id="softskills">
            @foreach (var s in Model.SoftSkills)
            {
                <span class="skill-badge">@s.SoftSkills</span>
            }
        </div>
    </div>
    <a href="~/lib/JoaoFrancaTEC.pdf" download class="botao-download"><i class="fas fa-download "></i>Baixar Currículo</a>
    <p>Atualizado em 01/08/2025</p>
</div>
<footer>
    <p>Site feito por João França utilizando ASP.NET Core Web App (MVC)</p>
</footer>

Views/Home/IndexHome.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "Apresentação";
}

    
<link rel="stylesheet" href="~/css/homestyle.css" asp-append-version="true" />

    <body class="d-flex justify-content-center align-items-center min-vh-100">
        <div class="containerH border-light bg-light text-black p-4 rounded-2 shadow text-sm-center mt-5 ">
            <h1 class="bemvindo display-4">Bem Vindo ao Meu Currículo!</h1>
            <p id="linha1" class="typing-text">
                Prazer! Me chamo João. Neste projeto irei apresentar minhas formações, experiências e conhecimentos.</p>
            <p id="linha2" class="typing-text">Clique em Start para conhecer melhor a minha jornada! </p>
        
    

            <a asp-controller="Curriculo" asp-action="CurriculoIndex" class="btn  align-items-center btn-primary mt-5 grow-hover">
            &rarr; START
            </a>
        </div>

     <script src="~/js/home.js"></script>

    </body>


    